# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - run: ls -lah
    - run: npm install yarn
    - run: yarn install
    - run: ls -lah
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr 
        path: node_modules/
        remote_path: ~/release/node_modules/
        remote_host: ${{ secrets.HOST }}
        remote_port: ${{ secrets.PORT }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SECRET_KEY }}
