# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - run: npm install yarn
    - run: yarn install
    - name: Stop pm2
      uses: appleboy/ssh-action@master 
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SECRET_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.MASTER_PATH }}
          pm2 stop CapedBaldy
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --exclude='.*' 
        path: ./
        remote_path: ${{ secrets.MASTER_PATH }}
        remote_host: ${{ secrets.HOST }}
        remote_port: ${{ secrets.PORT }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SECRET_KEY }}
    - name: Start pm2
      uses: appleboy/ssh-action@master 
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SECRET_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.MASTER_PATH }}
          pm2 start CapedBaldy
